{% set version = "0.7" %}

package:
  name: sphinxcontrib-napoleon
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sphinxcontrib-napoleon/sphinxcontrib-napoleon-{{ version }}.tar.gz
  sha256: 407382beed396e9f2d7f3043fad6afda95719204a1e1a231ac865f40abcbfcf8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pockets >=0.3
    - six >=1.5.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - sphinxcontrib
    - sphinxcontrib.napoleon

about:
  home: https://sphinxcontrib-napoleon.readthedocs.io
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Sphinx 'napoleon' extension"

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - ocefpaf
